### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by RogueMaster** [anfractuosity/flipperscope#3]
Latest firmware update caused compile issues... I made some changes to get it to compile, but if these aren't used, can they be removed?

https://github.com/RogueMaster/flipperzero-firmware-wPlugins/commit/f7dcf696891f6baa773de6e9ec795593073b0a36

**Comment by anfractuosity** [comment]
Thanks a lot for the heads up, just been looking into this.

I just pulled the latest dev branch of the firmware and found during compiling this app, it was unable to find one include file, which I've just symlinked to in my repo which seemed to let me then compile ok.

I wasn't sure what compilation error you got, but was wondering if you also symlinked to the stm32 libs, if the compilation errors might go away possibly? (Was thinking the stm32 headers may have changed recently)

**Comment by RogueMaster** [comment]
It was an error due to duplciated functions... they updated STM libraries

**Comment by anfractuosity** [comment]
Did you manage to resolve this out of interest.  It looks like you were able to revert the changes you made?

**Comment by RogueMaster** [comment]
I reverted the change that broke it due to other stuff not working, however, these files getting included correctly is still an issue... so will the duplicated functions be an issue when it compiles with latest OFW and unleashed...

**Comment by anfractuosity** [comment]
I just tried recently with the latest 'dev' branch from the official firmware, with the change I made yesterday to flipperscope, which did seem to compile ok.

I wonder if the issue you faced with duplicate definitions might be due a mismatch of the older STM32 files in your flipperscope directory and those in the firmware.

So it might be an idea to use symlinks instead possibly.

If you remove flipperscope and re-clone it, in the directory - `flipperzero-firmware-wPlugins/applications/external/`, you can use something like the following to update the symlinks I created to the correct location in your firmware.

```
cd flipperscope/lib/adc
rename -s '../../../../' '../../../../../' *.c

cd inc
rename -s '../../../../../' '../../../../../../' stm32wbxx_hal_tim.h
rename -s '../../../../../' '../../../../../../' stm32wbxx_nucleo_errno.h
rename -s '../../../../../' '../../../../../../' stm32wbxx_nucleo.h
```

`stm32wbxx_nucleo_errno.h` should point to the right location, when you update 'lib/STM32CubeWB' to the commit `06b8133fa`

Hope that helps

To clarify I used the `rename` tool, `rename from util-linux 2.38.1` - https://en.wikipedia.org/wiki/Util-linux (There is a different perl based tool apparently, which probably requires different syntax)

**Comment by RogueMaster** [comment]
That file, I can't find and does not exist. Could you fix this app so it doesn't show the dependencies not included error? Also, if you can, also fix to not use symlinks.

**Comment by anfractuosity** [comment]
Looks like the flipper zero firmware downgraded to an older version of the STM32 libs a few hours ago, so stm32wbxx_nucleo_errno.h became missing.

I've now bundled the actual STM32 headers etc. rather than using symlinks.

I wasn't sure what you meant by the `dependencies not included error` though?

The following is the compile output I get - 

```
 ./fbt launch_app APPSRC=applications_user/flipperscope
	CC	applications_user/flipperscope/scenes/scope_scene.c
	CC	applications_user/flipperscope/scenes/scope_scene_about.c
	CC	applications_user/flipperscope/scenes/scope_scene_run.c
	CC	applications_user/flipperscope/scenes/scope_scene_setup.c
	CC	applications_user/flipperscope/scenes/scope_scene_start.c
	CC	applications_user/flipperscope/scope.c
	CC	applications_user/flipperscope/lib/adc/stm32wbxx_hal_adc.c
	CC	applications_user/flipperscope/lib/adc/stm32wbxx_hal_adc_ex.c
	CC	applications_user/flipperscope/lib/adc/stm32wbxx_hal_rcc_ex.c
	CC	applications_user/flipperscope/lib/adc/stm32wbxx_hal_gpio.c
	CC	applications_user/flipperscope/lib/adc/stm32wbxx_hal_pwr.c
	CC	applications_user/flipperscope/lib/adc/stm32wbxx_hal.c
	CC	applications_user/flipperscope/lib/adc/stm32wbxx_hal_tim.c
	CC	applications_user/flipperscope/lib/adc/stm32wbxx_hal_tim_ex.c
	CC	applications_user/flipperscope/lib/adc/stm32wbxx_hal_cortex.c
	CC	applications_user/flipperscope/lib/adc/stm32wbxx_hal_dma.c
	CC	applications_user/flipperscope/lib/adc/stm32wbxx_hal_rcc.c
	APIPREP	build/f7-firmware-D/sdk_origin.i
	APIPP	build/f7-firmware-D/sdk_origin.i
	SDKCHK	firmware/targets/f7/api_symbols.csv
	AR	build/f7-firmware-D/.extapps/scope/libadc.a
	RANLIB	build/f7-firmware-D/.extapps/scope/libadc.a
	LINK	build/f7-firmware-D/.extapps/scope_d.elf
API version 23.0 is up to date
	APPMETA	build/f7-firmware-D/.extapps/scope.fap
	FAP	build/f7-firmware-D/.extapps/scope.fap
python3 "./scripts/runfap.py" -s build/f7-firmware-D/.extapps/scope.fap -t /ext/apps/Tools/scope.fap
	APPCHK	build/f7-firmware-D/.extapps/scope.fap
```
