### ISSUE TITLE
Update the flipperscope app for the SDK version 0.105 f7

### ISSUE THREAD

**Issue by furippa** [anfractuosity/flipperscope#6]
Hello!

Your flipperscope app version `0.2` fails to build with the SDK version `0.105.0-rc f7`. Please update the app in your repository and create a new pull request to the catalog repository with the updated manifest file.

> IMPORTANT: Don’t forget to update the app version and commit version in the manifest file.

[View logs](https://catalog.flipperzero.one/application/64bc656b13043e71ea7662f9/page)
[View build actions](https://github.com/flipperdevices/flipper-application-catalog/actions/runs/10316345359)

Flipper Team

**Comment by anfractuosity** [comment]
Just fixed and updated the changelog etc.
